Update sql schema and models
cs481-ekh/s24-illiterate-librarians pull request #173
Opened 2024-03-14 14:39 UTC by ALackey-ai

2024-03-14 18:14 UTC, AndrewDoering01 approved these changes

2024-03-14 20:47 UTC, ryesing approved these changes

2024-03-15 01:26 UTC, Connor-Thorpe01 approved these changes

2024-03-16 06:00 UTC, Connor-Thorpe01 requested changes
I have found a few things that I think we need to tweak think It would be easier to hop on a call sometime this week and fix them

2024-03-20 20:07 UTC, Connor-Thorpe01 approved these changes

2024-03-20 20:11 UTC, merged